### ISSUE TITLE
Not able to use Heracles.ts in my Project.

### ISSUE THREAD

**Issue by priyanshunayan** [HydraCG/Heracles.ts#117]
I was trying to experiment with hydra client and found it was reference implementation. So i decided to use it. I followed the instructions given in the Readme. I wrote the following code:
`import HydraClientFactory from "@hydra-cg/heracles.ts";
let hydraClient = HydraClientFactory.configure().withDefaults().andCreate();
const main = async () => {
    const resource = await hydraClient.getResource("http://localhost:8000/api");
}
main();`
And got the following error:
`/home/priyanshu/Documents/heracles-demo/node_modules/@hydra-cg/heracles.ts/src/HydraClientFactory.js:44
            .with(fetch.bind(window));
                             ^
ReferenceError: window is not defined
    at HydraClientFactory.withDefaults (/home/priyanshu/Documents/heracles-demo/node_modules/@hydra-cg/heracles.ts/src/HydraClientFactory.js:44:30)
    at Object.<anonymous> (/home/priyanshu/Documents/heracles-demo/main.ts:2:50)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Module.m._compile (/home/priyanshu/.nvm/versions/node/v10.16.0/lib/node_modules/ts-node/src/index.ts:858:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/priyanshu/.nvm/versions/node/v10.16.0/lib/node_modules/ts-node/src/index.ts:861:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)`

Any Help will be appreciated. Thank you.

**Comment by alien-mcl** [comment]
Hi @priyanshunayan 

Thank you for being interested in using both hydra and Heracles. I assume you're using node.js environment rather than web browser. Indeed window may be unavailable. I'll introduce a fix as soon as possible. Stay tuned!

**Comment by priyanshunayan** [comment]
@alien-mcl  Thanks that would be great. Also Readme seems to use top-level await keyword. Shouldn't it be inside async function?

**Comment by alien-mcl** [comment]
I've created a branch for that issue, `issue/117_Not_able_to_use_in_node_js_environment`. Is it possible for you to temporarely switch to that branch directly (package.json should allow that)?
I'll try to test it in node.js environment on my own, but this way it may be faster for you.

**Comment by priyanshunayan** [comment]
@alien-mcl Sure. No problem. Thank you very much.

**Comment by alien-mcl** [comment]
I've made another fix as it was not still working (I was able to create a client instance in pure node.js / JavaScript app). I'll try to publish it on npm ASAP.

**Comment by alien-mcl** [comment]
I've published latest Herales.ts version 0.5.1 to npm which should resolve your issue. Feel free to reopen it if it still doesn't work. In case of other issues, just raise more bugs - I'll be happy to resolve them!
